services:
  jobmanager:
    image: flink:latest
    depends_on:
      - cloud
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - aware-network

  taskmanager:
    image: flink:latest
    command: taskmanager
    depends_on:
      - jobmanager
    networks:
      - aware-network

  # Single Application
  # jobmanager:
  #   image: flink:latest
  #   depends_on:
  #     - cloud
  #   ports:
  #     - "8081:8081"
  #   command: standalone-job --jars /opt/flink/usrlib/rumble.jar, --jars /opt/flink/usrlib/table-test.jar # standalone-job --job-classname com.flink.analytic.TableTest --jars /opt/flink/usrlib/table-test.jar
  #   volumes:
  #     - ../flink-jobs:/opt/flink/usrlib
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       parallelism.default: 2
  #   networks:
  #     - aware-network    

  # taskmanager:
  #   image: flink:latest
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   scale: 1
  #   volumes:
  #     - ../flink-jobs:/opt/flink/usrlib
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       taskmanager.numberOfTaskSlots: 4
  #       parallelism.default: 4
  #   networks:
  #     - aware-network
    
  # sql-client:
  #   build: ../flink/sql-client/.
  #   command: bin/sql-client.sh
  #   depends_on:
  #     - jobmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       rest.address: jobmanager    
  #   networks:
  #     - aware-network    

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - aware-network

  kafka:
    image: docker.io/bitnami/kafka:2.8
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9093,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zookeeper
    networks:
      - aware-network

  cloud:
    image: cloud
    hostname: cloud
    container_name: cloud
    depends_on:
      - zookeeper
    environment:
      BROKER: kafka
      PORT: 9093
      TOPIC: traffic
      URL: https://api.airplanes.live/v2/point/36.1716/-115.1391/200
    networks:
      - aware-network
  
  puddle:
    image: puddle
    hostname: puddle
    container_name: puddle
    depends_on:
      - cloud
    environment:
      BROKER: kafka
      PORT: 9093
      TOPIC: traffic
    networks:
      - aware-network
  
  # turbine:
  #   container_name: turbine1
  #   image: turbine
  #   ports:
  #     - 5001:5001
  #   depends_on:
  #     - cloud
  #   volumes:
  #     - "../models:/root/models"
  #   networks:
  #     - aware-network

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  runway:
    container_name: runway
    image: runway
    ports:
      - 8000:8000
    networks:
      - aware-network

networks:
  aware-network:
    driver: bridge
    name: aware_network
